### PR TITLE
Automate gh release

### PR DESCRIPTION
**Pull request by jerger**
Okay, did some trial & error work for setting up a somehow working CI ...

* We should have a test status badge on our README
* PRs should now been tested by GitHub Actions
* If we tag (the master) with sth like 0.1.2, this should trigger a release build with resulting artifact in GH releases.

Regadring npm I found out how we can start (see package.json). I did a manual triggered publish already so you can test with

```
sudo npm i mastodon-bot@0.1.0-dev-1 -g
mastodon-bot -h
```

### CODE REVIEW

**Comment by yogthos** [comment]
That looks fantastic, I'm good to merge in if you are. :)

**Comment by jerger** [comment]
go on your mark :-)

maybe want to try the tagging thing?

**Comment by yogthos** [comment]
Yeah sure, I'll merge in and make a tag then. :)

**Comment by yogthos** [comment]
I bumped up package.json to 1.0.0, and pushed a tag v1.0.0, might as well treat it as the official a 1.0 release. :)

**Comment by jerger** [comment]
the tags name should either be 1.0.0 or you may insert a 'v' here: https://github.com/yogthos/mastodon-bot/blob/27c99a7d556727089da0d1f7ec486de43fc2a5ff/.github/workflows/release.yml#L4

**Comment by yogthos** [comment]
ah my bad, just fixed it

**Comment by jerger** [comment]
hmm ... it still is publishing as pre release ...
Will adjust and search how to publish to npm also ... in the next PR :-)

**Pull request merged**
