### PR TITLE
Refactoring: Introduce spec & more modulare ns

### PR DESCRIPTION
**Pull request by jerger**
work is ready for a first inspection & discussion. The project now compiles, repl works & spec is in place for the mastodon part. 

There might be the chance, that the whole thing works, but I've to find & fix my auth-issue, so I can not validate.

Nevertheless, I'm curious for your early review & comments :-)

### CODE REVIEW

**Comment by yogthos** [comment]
Overall, seems reasonable to me. I'm not sure there's much value in making config keywords namespaces though. Spec allows handling unqualified keys, documented in [entry maps](https://clojure.org/guides/spec#_entity_maps) section. This would also address the issue of making them play nice with Js interop.

**Comment by jerger** [comment]
Switching back to unqualified keywords was a really good hint :-)
I found some more places where I missed the use of the namespaced version.
Maybe I should search for automated refactoring tools in my setup ...

**Comment by yogthos** [comment]
Nice, and yeah there are a few decent refactoring tools for Emacs, [clj-refactor](https://github.com/clojure-emacs/clj-refactor.el) and [refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl) are both pretty good from what I hear. I use Cursive myself, but it's commercial. Definitely easier when you can refactor things automatically.

And happy to merge stuff if you think the changes are ready, I saw posting is confirmed to work. :)

**Comment by jerger** [comment]
Let me do some additional test (e.g. posting images).
And I want to be able to reproduce #issue24 or confirm it's closed now.

**Comment by jerger** [comment]
Okay, the pull request is ready to be merged from my point of view.

I finished testing (and found two more bugs in my refactoring :-)

#issue24 I can no longer reproduce - I will close it.

BTW: I'm using vs-code & calva. Refactoring support will arrive soon also on my env :-)

**Comment by yogthos** [comment]
Awesome, everything looks good to me as well. And Calva is pretty decent overall, I use it myself for some projects. It also works with [clj-kondo](https://github.com/borkdude/clj-kondo), I recommend taking a look at it if you haven't. It's quite good at finding things like mismatched arguments, unused variables, name mismatches, and so on.

**Pull request merged**
